# ─────────────────────────────────────────────────────────────────
# ROLE: Cấu hình Chạy tự động (Run Variables)
# FILE: run_config_local.yaml
# DESCRIPTION: Cấu hình dagster ops, tham số truyền vào input khi chạy thủ công.
# ─────────────────────────────────────────────────────────────────

ops: {}
resources: {}
